use_frameworks!

platform :ios, '9.0'

warn_for_unused_master_specs_repo => false

target 'ZBOrientation_Example' do
  pod 'ZBOrientation', :path => '../'

  target 'ZBOrientation_Tests' do
    inherit! :search_paths

    
  end
end
